### ISSUE TITLE
System crashing first use

### ISSUE THREAD

**Issue by TremorJay** [pbremer/voicemail-system#1]
Briefly: my steps

downloaded 'voicemail-system-master'
extracted to desktop
created desktop shortcut for application 'CIS 376 Voicemail System'
ran vm-sys/set-data.bat
placed my .wav file in vm-sys/vm/1/248/365/9497/vm/new/
ran application with desktop shortcut
input 12483659497#
console crashes

**Comment by pbremer** [comment]
i believe it is because vm-sys is not in the correct locaton on your computer. ensure that the vm-sys folder is located in your home directory (in the command prompt execute "echo %USERPROFILE%" and that is where you should place the vm-sys folder) i will work on fixing the set-data batch script to make usage easier
